### ISSUE TITLE
Update incidents api controller to take missing params

### ISSUE THREAD

**Issue by Jlawlzz** [Seed-Inc/seed_web#21]
- Date of incident (unless :start_time is in epoch time?)
- Emergency response time - string
- User's expectation of incident (went as expected, did not go as expected) - string

**Comment by kidbombay** [comment]
What is emergency response time?

**Comment by Jlawlzz** [comment]
The question in the bot is: 

Question:
 "Okay. How long did it take for them to get there?"

Answer:
"Less than 2 minutes"
"2-5 minutes"
"5-10 minutes"
"10-30 minutes"
"Over 30 minutes"

**Comment by kidbombay** [comment]
Are we always storing this as a string? Will the options change in the future?

**Comment by Jlawlzz** [comment]
These could change in the future although it seems unlikely. I think string would be the safest option, I could send you numbers in something like an array instead though

**Comment by kidbombay** [comment]
http://theseedapp.com/docs#incidents-update-a-incident start time added
What is User's expectation of incident?

**Comment by Jlawlzz** [comment]
"When the police officer was interacting with you, did it go like you expected it to?"

"Yes" or "No"

Could be saved as a bool

**Comment by kidbombay** [comment]
Do you have the full list of bot questions?
This one seems at odds with the rating data which is 1-5?
