### ISSUE TITLE
Update users api controller to take missing user params

### ISSUE THREAD

**Issue by Jlawlzz** [Seed-Inc/seed_web#22]
User Race,
User Gender, 
User Birthdate,

**Comment by kidbombay** [comment]
How do you want to pass dates to the api?

**Comment by Jlawlzz** [comment]
What do you think about saving everything in epoch time?

**Comment by kidbombay** [comment]
Well database saves in postgres time stamps. Happy to accept timestamps in unix time.

**Comment by kidbombay** [comment]
Race and gender are tables so you would have to pass the id once you have it.

**Comment by Jlawlzz** [comment]
Ya thats fine, ill just shoot an update to users

**Comment by kidbombay** [comment]
Two new end points - 
http://theseedapp.com/docs#races-get-all-races
http://theseedapp.com/docs#genders-get-all-genders

And user end point updated with gender id and race id
http://theseedapp.com/docs#users-update-a-user

**Comment by kidbombay** [comment]
User endpoint updated with birthday option

**Comment by Jlawlzz** [comment]
Awesome, thanks!
