### ISSUE TITLE
Update for Gender & Race endpoints

### ISSUE THREAD

**Issue by Jlawlzz** [Seed-Inc/seed_web#27]
# Race:
asian,
black/african,
hispanic/latino,
middle eastern,
multiracial,
native american,
pacific islander,
south asian,
white/caucasian,
couldn't tell

# Gender:
man,
woman,
other,
couldn't tell

# Gender-Identification:
intersexual,
transgender,
opt-out,
n/a

**Comment by kidbombay** [comment]
These can just be edited in Admin
