### ISSUE TITLE
New Fields

### ISSUE THREAD

**Issue by Jlawlzz** [Seed-Inc/seed_web#28]
# Incident

## type of incident: string 
[conversation, citation, crime, arrest, police shooting, other]

## catalyst of incident: string 
[called the police, got pulled over, got stopped on foot, witnessed police, other]

## result of incident: string 
[helped you, wanted information, ticketed you, gave you a warning, arrested you, did nothing, other]

## property searched?:  boolean
[yes / no]

## permission for search?: boolean
[yes/no]

## emergency?: boolean
[yes/no]

## emergency response time: string/number?
[less than 2 minutes, 2-5 minutes, 5-10 minutes, 10-30 minutes, over 30 minutes]

## number of officers on scene: number

# Officer

## age: string/number?
[20-30, 31-40, 41-50, over 50, couldn't tell]

**Comment by kidbombay** [comment]
Type of incident makes sense to add as field but can we do the other fields as part of the custom JSON?

**Comment by Jlawlzz** [comment]
Yep, that works for me, what is the endpoint for custom json? Looking in the docs.

**Comment by kidbombay** [comment]
Ah crap, never documented. Will update today.

**Comment by Jlawlzz** [comment]
👍  Thanks

**Comment by kidbombay** [comment]
@Jlawlzz http://raheem.ai/docs#incidents-create-a-incident has metadata field now where you can store JSON.
