### ISSUE TITLE
Add Ability for Admins to manage races

### ISSUE THREAD

**Issue by kidbombay** [Seed-Inc/seed_web#8]
- [x] Only admins can see /races
- [x] Only admins can edit/delete race
- [x] Only admins can create race
- [x] regular users aren't able to see /races or or a single race /race/1
- [x] Allow ordering of races by position column. Lower positions come first.

**Comment by kidbombay** [comment]
Test at http://theseedapp.com/races

**Comment by BrandonAnderson** [comment]
tested and all good.
